name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REACT_APP_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
      REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
      REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
      REACT_APP_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build -- --no-warnings

      - name: Deploy to GitHub Pages
        run: |
          # Your deployment command here, for example:
          # npx gh-pages -d build
          npx gh-pages -d build -u "dominic-g" -b "gh-pages" -t "${{ secrets.REACT_TOKEN }}"

        env:
          CI: false
          GENERATE_SOURCEMAP: false
